joblens:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'postgres') }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASS', 'postgres') }}"
      port: 5432
      dbname: joblens
      schema: public
      threads: 4
      connect_timeout: 10
